import {mkdir,rm,copyFile,readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
const site=JSON.parse(await readFile('content/site.json','utf8'));
const origin='https://wmiegroup.com';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const nav=[['/','Home'],['/about/','About'],['/services/','Services'],['/industries/','Industries'],['/leadership/','Leadership'],['/contact/','Contact']];
const orgId=origin+'/#organization';
const org={'@type':'Organization','@id':orgId,name:'WMIE Group',alternateName:'Wholesale Management & Infrastructure Expansion',url:origin+'/',logo:origin+'/assets/logo-96.webp',description:'Business development and strategic partnership support with established telecommunications, infrastructure, and commercial risk-readiness expertise.',member:site.people.map(p=>({'@type':'OrganizationRole',roleName:'Co-Owner',member:{'@type':'Person','@id':origin+'/leadership/#'+p.slug,name:p.name,jobTitle:p.role,description:p.bio}}))};
const cta=(label='Discuss a Business Opportunity')=>`<div class="cta-row"><a class="btn primary" href="/contact/">${esc(label)}</a><a class="btn" href="/services/">Explore Services</a></div>`;
const cards=()=>`<div class="service-grid">${site.services.map(s=>`<article class="tile"><h3><a href="${s.path}">${esc(s.name)}</a></h3><p>${esc(s.description)}</p><a href="${s.path}">Explore ${esc(s.name)} →</a></article>`).join('')}</div>`;
const people=()=>`<div class="team-grid">${site.people.map(p=>`<article class="person ${p.slug}" id="${p.slug}"><div class="photo"><img src="/assets/${p.slug}.webp" alt="${esc(p.name)} — Co-Owner of WMIE" width="${p.width}" height="${p.height}" loading="lazy" decoding="async"></div><div class="person-body"><h3>${esc(p.name)}</h3><p>Co-Owner</p><p>${esc(p.role)}</p><details class="profile"><summary>View ${esc(p.name)}’s Profile</summary><p>${esc(p.bio)}</p></details></div></article>`).join('')}</div>`;
const section=(id,h,body)=>`<section class="section" id="${id}"><div class="panel copy"><h2>${esc(h)}</h2>${body}</div></section>`;
const paragraph=t=>`<p>${esc(t)}</p>`;
const contactLinks=`<div class="contact-grid"><div class="contact-card"><h2 class="hero-heading">Email a Co-Owner</h2><p><a href="mailto:Janie@wmie.org">Janie@wmie.org</a><br><a href="mailto:David@wmie.org">David@wmie.org</a><br><a href="mailto:Todd@wmie.org">Todd@wmie.org</a></p></div><div class="contact-card"><h2 class="hero-heading">Connect on LinkedIn</h2><div class="link-row"><a class="btn" href="https://www.linkedin.com/in/toddsegress" target="_blank" rel="noopener noreferrer">Todd Segress</a><a class="btn" href="https://www.linkedin.com/in/janie-meadows-734129353" target="_blank" rel="noopener noreferrer">Janie Meadows</a><a class="btn" href="https://www.linkedin.com/in/david-stephens-19131343/" target="_blank" rel="noopener noreferrer">David Stephens</a></div></div></div>`;
const form=`<form class="contact-form" id="opportunity-form" name="business-opportunity" method="POST" action="/thank-you/" data-netlify="true" netlify-honeypot="bot-field" hidden>
<input type="hidden" name="form-name" value="business-opportunity"><p hidden><label>Leave this field empty: <input name="bot-field" tabindex="-1" autocomplete="off"></label></p>
<div class="form-grid">
<div class="field"><label for="company">Company or Organization *</label><input id="company" name="company" autocomplete="organization" required minlength="2" maxlength="160"></div>
<div class="field"><label for="name">Your Name *</label><input id="name" name="name" autocomplete="name" required minlength="2" maxlength="100"></div>
<div class="field"><label for="email">Email *</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254"></div>
<div class="field"><label for="phone">Phone (optional)</label><input id="phone" name="phone" type="tel" autocomplete="tel" maxlength="40"></div>
<div class="field"><label for="industry">Industry *</label><select id="industry" name="industry" required><option value="">Choose your industry</option><option>Telecommunications &amp; Broadband</option><option>Infrastructure &amp; Construction</option><option>Corporate / Professional Services</option><option>Public Sector / Tribal Organization</option><option>Other</option></select></div>
<div class="field"><label for="inquiry">Inquiry Type *</label><select id="inquiry" name="inquiry" required><option value="">Choose the support you need</option>${site.services.map(s=>`<option>${esc(s.name)}</option>`).join('')}<option>Other / General Inquiry</option></select></div>
<div class="field full"><label for="project">Opportunity or Project Description *</label><textarea id="project" name="project" required minlength="20" maxlength="4000" aria-describedby="project-help"></textarea><p class="form-note" id="project-help">Include the location, current stage, timeline, and support you need. Please do not include confidential financial records or identification documents.</p></div>
</div><p class="form-note">We use the information you provide to review and respond to your inquiry. Submitting an inquiry does not create an advisory, insurance, engineering, or legal engagement.</p><div class="cta-row"><button class="btn primary" type="submit">Send Business Inquiry</button></div></form>`;
// Netlify strips data-netlify only when form detection is enabled. Keep email contact usable
// everywhere, and expose the optional form only after that processing is verified in HTML.
const formScript=`<script src="/assets/contact.js" defer></script>`;
const pages=[
{path:'/',title:'WMIE Group | Strategic Partnerships & Business Development',description:'WMIE helps companies develop partnerships and pursue business opportunities, with established telecommunications, infrastructure, and commercial risk expertise.',h1:'Strategic Partnerships. Business Development. Infrastructure Opportunities.',lead:'WMIE Group helps companies and organizations develop strategic partnerships, pursue new business opportunities, and navigate complex projects through experienced leadership and specialized industry relationships.',body:`<section class="section" id="home"><div class="hero-grid"><div><p class="kicker">Oklahoma-based · Business-focused</p><h1>Strategic Partnerships.<br>Business Development.<br>Infrastructure Opportunities.</h1><p class="company-name">WMIE — Wholesale Management &amp; Infrastructure Expansion</p><p class="lead">WMIE Group helps companies and organizations develop strategic partnerships, pursue new business opportunities, and navigate complex projects through experienced leadership and specialized industry relationships.</p>${cta()}</div><aside class="hero-card"><div><p class="kicker">We Make It Easy</p><h2 class="hero-heading">Clear strategy. Strong relationships. Practical readiness.</h2></div><p>Our established experience in telecommunications, infrastructure, and commercial risk informs support for companies pursuing growth and complex opportunities.</p><a class="btn" href="/leadership/">Meet the Co-Owners</a></aside></div></section>
${section('about','Business growth starts with alignment.',paragraph('Bring together your opportunity, your message, and the relationships needed to move forward. WMIE supports sales development, corporate and tribal partner communication, infrastructure readiness, and commercial risk conversations.')+'<a href="/about/">About WMIE →</a>')}
${section('services','Explore Our Services',cards())}
${section('sales-marketing','Business Development & Marketing',paragraph('Prepare your positioning, outreach strategy, and partner-ready presentations for the next opportunity.')+'<a href="/services/business-development/">Business development support →</a>')}
${section('bandwidth-partnerships','Strategic & Bandwidth Partnerships',paragraph('Develop corporate relationships and explore bandwidth opportunities while providers handle service delivery and operations.')+'<a href="/services/strategic-partnerships/">Explore partnership support →</a>')}
${section('engineering-readiness','Infrastructure & Engineering Readiness',paragraph('Coordinate project-readiness conversations and access engineering support through referral pathways. WMIE does not perform engineering work.')+'<a href="/services/infrastructure/">Infrastructure opportunity support →</a>')}
${section('insurance-surety-bonds','Insurance & Bonding Coordination',paragraph('Discuss commercial risk and project requirements with a clear distinction between WMIE’s strategic support and specialist insurance or surety services.')+'<a href="/services/insurance-bonding/">Insurance and bonding coordination →</a>')}
${section('tribal-corporate-relations','Tribal & Corporate Relations',paragraph('Prepare for stakeholder conversations with respect and clarity. Tribal relations are one specialized capability within our broader partnership work.')+'<a href="/services/tribal-government-relations/">Relationship support →</a>')}
${section('team','Meet the Co-Owners',people()+'<a href="/leadership/">Leadership and experience →</a>')}
${section('contact','Discuss Your Next Opportunity',paragraph('Tell us about your organization, the opportunity, and the support you need.')+cta('Contact WMIE'))}`},
{path:'/about/',title:'About WMIE Group | Business Growth & Partnerships',description:'Learn how WMIE combines business development, strategic relationships, and telecommunications and infrastructure experience to support complex opportunities.',h1:'Business Growth Through Strategy & Relationships',lead:'WMIE brings business development, partner alignment, and project-readiness support into one strategic conversation.',body:section('who-we-are','Wholesale Management & Infrastructure Expansion',paragraph('WMIE is an Oklahoma-based business development and strategic partnerships firm. Its established expertise includes telecommunications, broadband infrastructure, commercial risk readiness, and corporate and tribal relationships.')+paragraph('The company’s name reflects its infrastructure roots; its work also includes sales development, marketing alignment, and opportunity positioning for companies and organizations pursuing growth. “We Make It Easy” is the brand’s commitment to clear communication around complex opportunities.'))+section('how-we-work','A Clear Role in a Complex Opportunity',paragraph('WMIE directly supports positioning, outreach planning, proposal communication, partner engagement, and readiness conversations. Engineering work is performed by engineering providers. Bandwidth providers manage service delivery and operations. Insurance placement, underwriting, and bond issuance belong with appropriately authorized specialists.')+paragraph('Begin with an opportunity discussion. Explain your organization, project stage, location, current partners, and goals. The next step is to establish a suitable scope and identify where specialist involvement is needed. No contract, grant, coverage, or bonding result is guaranteed.')+'<div class="section-links"><a href="/services/">Services</a><a href="/industries/">Industry focus</a><a href="/leadership/">Meet the leadership team</a></div>'+cta())},
{path:'/services/',title:'WMIE Services | Business Development & Strategic Partnerships',description:'Explore WMIE’s business development, strategic partnerships, infrastructure readiness, insurance and bonding coordination, and stakeholder relationship support.',h1:'Support for Growth, Partnerships & Complex Opportunities',lead:'Start with the business problem. We can discuss the mix of communication, relationships, readiness, and specialist coordination your opportunity needs.',body:section('service-options','Where WMIE Can Help',cards())+section('direct-and-partner','Strategic Support, with Clear Specialist Roles',paragraph('WMIE supports business positioning, sales development, marketing alignment, partner engagement, and project-readiness conversations. Engineering providers perform engineering work; bandwidth providers operate and deliver services; authorized insurance and surety specialists handle their respective placements and approvals.')+paragraph('A discussion establishes the relevant scope. Our website does not imply legal advice, government representation, licensed engineering, insurance underwriting, or guaranteed contract and funding outcomes.')+cta())},
{path:'/industries/',title:'Industry Focus | WMIE Group',description:'WMIE’s established telecommunications, broadband, and infrastructure expertise supports business-development, partnership, and commercial risk-readiness conversations.',h1:'Industry Experience That Informs Broader Business Growth',lead:'Telecommunications and infrastructure are our established foundation. Business development and relationship support connect that experience to a company’s specific opportunity.',body:section('telecommunications','Telecommunications & Broadband',paragraph('WMIE’s existing experience includes telecommunications, broadband expansion, fiber infrastructure, and bandwidth-sales partnerships. Organizations can discuss opportunity positioning, corporate and tribal stakeholder alignment, and project-readiness needs.')+'<a href="/services/infrastructure/">Infrastructure support →</a>')+section('infrastructure-construction','Infrastructure & Project Organizations',paragraph('Infrastructure opportunities combine organizational readiness, technical providers, contractual requirements, and relationships. WMIE supports the strategic conversation and coordination around those needs; engineering and construction delivery remain with the companies performing that work.')+'<a href="/services/insurance-bonding/">Commercial risk readiness →</a>')+section('corporate-growth','Corporate Growth & Strategic Relationships',paragraph('Sales development, proposal positioning, marketing alignment, and partner communication support companies pursuing new business. WMIE evaluates the actual opportunity and fit rather than advertising specialist expertise in every industry.')+paragraph('If your organization operates in another sector, describe the opportunity and the support you are seeking. We can discuss whether the need aligns with the team’s established capabilities before agreeing a scope.')+'<a href="/services/business-development/">Business development support →</a>'+cta('Explore a Partnership'))},
{path:'/leadership/',title:'WMIE Leadership | Todd Segress, Janie Meadows & David Stephens',description:'Meet WMIE co-owners Todd Segress, Janie Meadows, and David Stephens, with experience in telecommunications, infrastructure, insurance strategy, and risk management.',h1:'Meet the WMIE Co-Owners',lead:'Experienced leadership across telecommunications, infrastructure development, commercial insurance strategy, and organizational relationships.',body:section('owners','Leadership & Experience',people())+section('talk-to-the-team','Start with a Business Conversation',paragraph('Discuss your organization’s goals, the parties involved, and the type of support needed. The team can clarify whether an opportunity calls for business-development work, partnership alignment, or a conversation with a specialist provider.')+contactLinks+cta())},
{path:'/contact/',title:'Contact WMIE Group | Discuss a Business Opportunity',description:'Contact WMIE’s co-owners about business development, strategic partnerships, infrastructure opportunities, stakeholder relations, or commercial risk readiness.',h1:'Discuss a Business Opportunity',lead:'Tell us about your organization, your goal, and the support you need. We’ll use your inquiry to understand the opportunity and discuss an appropriate next step.',body:section('contact-options','Contact WMIE',contactLinks+paragraph('Include your company, contact details, industry, project location, current stage, and timeline in your inquiry.')+form)+section('what-to-expect','A Clear Starting Point',paragraph('An initial inquiry helps the team assess fit and identify the right conversation. The scope of any work is agreed separately. Please use an initial inquiry for a general description, rather than sensitive financial or identification documents.')),script:formScript},
{path:'/thank-you/',title:'Inquiry Received | WMIE Group',description:'Thank you for contacting WMIE Group.',h1:'Thank You for Your Inquiry',lead:'Your inquiry has been submitted. If you need to add details, contact one of our co-owners by email.',body:section('next-step','Keep the Conversation Going',contactLinks+'<a href="/">Return to WMIE</a>'),noindex:true}
];
for(const s of site.services) pages.push({path:s.path,title:`${s.name} | WMIE Group`,description:s.description,h1:s.name,lead:s.lead,service:s,body:s.sections.map(([h,...items],i)=>section('section-'+(i+1),h,items.map(x=>Array.isArray(x)?'<ul>'+x.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>':paragraph(x)).join(''))).join('')+section('next-step','Discuss Your Opportunity',cta()+`<div class="section-links">${site.services.filter(x=>x.path!==s.path).map(x=>`<a href="${x.path}">${esc(x.name)}</a>`).join('')}</div>`)});
function render(p){
 const url=origin+p.path;
 const graph=[org,{'@type':'WebSite','@id':origin+'/#website',url:origin+'/',name:'WMIE Group',publisher:{'@id':orgId},inLanguage:'en-US'}];
 if(p.path!=='/'&&!p.noindex)graph.push({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:origin+'/'},...(p.service?[{'@type':'ListItem',position:2,name:'Services',item:origin+'/services/'},{'@type':'ListItem',position:3,name:p.h1,item:url}]:[{'@type':'ListItem',position:2,name:p.h1,item:url}])]});
 if(p.service)graph.push({'@type':'Service',name:p.service.name,description:p.description,url,provider:{'@id':orgId},serviceType:p.service.name});
 const breadcrumbs=p.path==='/'?'':`<nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span>${p.service?'<a href="/services/">Services</a><span aria-hidden="true">/</span>':''}<span>${esc(p.h1)}</span></nav>`;
 return `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.title)}</title><meta name="description" content="${esc(p.description)}"><link rel="canonical" href="${url}">${p.noindex?'<meta name="robots" content="noindex">':''}<meta property="og:title" content="${esc(p.title)}"><meta property="og:description" content="${esc(p.description)}"><meta property="og:type" content="website"><meta property="og:site_name" content="WMIE Group"><meta property="og:locale" content="en_US"><meta property="og:url" content="${url}"><meta property="og:image" content="${origin}/assets/social-preview.jpg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="WMIE — We Make It Easy"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(p.title)}"><meta name="twitter:description" content="${esc(p.description)}"><meta name="twitter:image" content="${origin}/assets/social-preview.jpg"><meta name="twitter:image:alt" content="WMIE — We Make It Easy"><link rel="icon" type="image/webp" href="/assets/logo-96.webp"><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c')}</script></head><body><a class="skip-link" href="#main">Skip to content</a><div class="bg" aria-hidden="true"></div><header class="topbar"><a class="brand" href="/" aria-label="WMIE Home"><span class="mark"><img src="/assets/logo-96.webp" alt="WMIE logo" width="42" height="42"></span><span>WMIE<small>WE MAKE IT EASY</small></span></a><nav class="nav" aria-label="Main navigation">${nav.map(([path,label])=>`<a href="${path}"${p.path===path?' aria-current="page"':''}>${label}</a>`).join('')}</nav></header><main id="main">${p.path==='/'?'':`<section class="section page-hero">${breadcrumbs}<p class="kicker">WMIE Group · We Make It Easy</p><h1>${esc(p.h1)}</h1><p class="lead">${esc(p.lead)}</p></section>`}${p.body}</main><footer><p>WMIE — Wholesale Management &amp; Infrastructure Expansion</p><p>Oklahoma-based · We Make It Easy</p><a href="/contact/">Contact WMIE</a></footer>${p.script||''}</body></html>\n`;
}
await rm('dist',{recursive:true,force:true});await mkdir('dist/assets',{recursive:true});
for(const file of ['todd.webp','janie.webp','david.webp','logo-96.webp','social-preview.jpg','site.css','contact.js'])await copyFile('assets/'+file,'dist/assets/'+file);
for(const p of pages){const dir=join('dist',p.path);await mkdir(dir,{recursive:true});await writeFile(join(dir,'index.html'),render(p));}
await copyFile('404.html','dist/404.html');
await writeFile('dist/robots.txt',`User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`);
await writeFile('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+pages.filter(p=>!p.noindex).map(p=>`<url><loc>${origin+p.path}</loc></url>`).join('')+'</urlset>\n');
console.log(`Built ${pages.length} static pages; ${pages.filter(p=>!p.noindex).length} indexable URLs; historical files excluded.`);
